export default {
  name: "Wild And Wet",
  releaseDate: 1604079000000,
  description:
    "Double your trouble with Avery and Jill - two naughty girls who will stop at nothing to get a man’s attention. Nobody needs to know, and when these ladies pounce, you won’t know what hit you.",
  actors: ["Avery Cristy", "Jill Kassidy", "Michael Stefano"],
  custom: {
    director: "Laurent Sky",
  },
  labels: [
    "69",
    "ball sucking",
    "blonde",
    "blowjob",
    "cum in mouth",
    "cum swapping",
    "deep throat",
    "doggystyle",
    "double blowjob",
    "face sitting",
    "facial",
    "ffm",
    "hairy pussy",
    "handjob",
    "lingerie",
    "missionary",
    "oil",
    "pussy licking",
    "riding",
    "rimming",
    "shaved",
    "small tits",
    "threesome",
  ],
};
